spring.application.name=gameportal
# Baza danych
spring.datasource.url=jdbc:postgresql://localhost:5432/gameportal
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Port aplikacji
server.port=8080

#Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.model-converters.pageable-converter.enabled=true

#JWT
jwt.secret=3e7a9f2b1c8d4e6f0a3b5c7d9e1f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f
jwt.expiration=86400000