spring.application.name=gameportal
# Baza danych
spring.datasource.url=jdbc:postgresql://localhost:5432/gameportal
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Port aplikacji
server.port=8080

#Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.model-converters.pageable-converter.enabled=true