spring.application.name=gameportal
# Baza danych
spring.datasource.url=jdbc:postgresql://localhost:5432/gameportal
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Port aplikacji
server.port=8080